//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackBookHitChoice.IccVinService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cpi/core/simple_fault")]
    public partial class SimpleFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string faultMessageTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string FaultMessageText {
            get {
                return this.faultMessageTextField;
            }
            set {
                this.faultMessageTextField = value;
                this.RaisePropertyChanged("FaultMessageText");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cpi/core/status_information")]
    public partial class StatusInformation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Error[] errorField;
        
        private string statusCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Error", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Error[] Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("Error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("StatusCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cpi/core/error")]
    public partial class Error : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorCodeField;
        
        private string cPIErrorCodeField;
        
        private string errorDescriptionField;
        
        private string errorSeverityLevelField;
        
        private string errorSourceIdentifierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CPIErrorCode {
            get {
                return this.cPIErrorCodeField;
            }
            set {
                this.cPIErrorCodeField = value;
                this.RaisePropertyChanged("CPIErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ErrorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
                this.RaisePropertyChanged("ErrorDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ErrorSeverityLevel {
            get {
                return this.errorSeverityLevelField;
            }
            set {
                this.errorSeverityLevelField = value;
                this.RaisePropertyChanged("ErrorSeverityLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ErrorSourceIdentifier {
            get {
                return this.errorSourceIdentifierField;
            }
            set {
                this.errorSourceIdentifierField = value;
                this.RaisePropertyChanged("ErrorSourceIdentifier");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cpi/core/vin_information")]
    public partial class VINInformation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vehicleIdentificationNumberField;
        
        private string manufacturersNameField;
        
        private string modelNameField;
        
        private string modelYearField;
        
        private string postalStateAbbreviationField;
        
        private string vehicleCollisionSymbolField;
        
        private string vehicleComprehensiveSymbolField;
        
        private string vehicleSymbolCodeField;
        
        private string vehiclePerformanceCodeField;
        
        private string averageRetailPriceAmountField;
        
        private string vehicleOriginalCostNewAmountField;
        
        private string passiveRestraintCodeField;
        
        private string antiLockBrakeCodeField;
        
        private string daytimeRunningLightsCodeField;
        
        private string vehicleBodyTypeDescriptionField;
        
        private string iSOAntiTheftDeviceCodeField;
        
        private string vehiclePersonalInjuryProtectionSymbolField;
        
        private string vehicleLiabilitySymbolField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string VehicleIdentificationNumber {
            get {
                return this.vehicleIdentificationNumberField;
            }
            set {
                this.vehicleIdentificationNumberField = value;
                this.RaisePropertyChanged("VehicleIdentificationNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ManufacturersName {
            get {
                return this.manufacturersNameField;
            }
            set {
                this.manufacturersNameField = value;
                this.RaisePropertyChanged("ManufacturersName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ModelName {
            get {
                return this.modelNameField;
            }
            set {
                this.modelNameField = value;
                this.RaisePropertyChanged("ModelName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ModelYear {
            get {
                return this.modelYearField;
            }
            set {
                this.modelYearField = value;
                this.RaisePropertyChanged("ModelYear");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string PostalStateAbbreviation {
            get {
                return this.postalStateAbbreviationField;
            }
            set {
                this.postalStateAbbreviationField = value;
                this.RaisePropertyChanged("PostalStateAbbreviation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string VehicleCollisionSymbol {
            get {
                return this.vehicleCollisionSymbolField;
            }
            set {
                this.vehicleCollisionSymbolField = value;
                this.RaisePropertyChanged("VehicleCollisionSymbol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string VehicleComprehensiveSymbol {
            get {
                return this.vehicleComprehensiveSymbolField;
            }
            set {
                this.vehicleComprehensiveSymbolField = value;
                this.RaisePropertyChanged("VehicleComprehensiveSymbol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string VehicleSymbolCode {
            get {
                return this.vehicleSymbolCodeField;
            }
            set {
                this.vehicleSymbolCodeField = value;
                this.RaisePropertyChanged("VehicleSymbolCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string VehiclePerformanceCode {
            get {
                return this.vehiclePerformanceCodeField;
            }
            set {
                this.vehiclePerformanceCodeField = value;
                this.RaisePropertyChanged("VehiclePerformanceCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string AverageRetailPriceAmount {
            get {
                return this.averageRetailPriceAmountField;
            }
            set {
                this.averageRetailPriceAmountField = value;
                this.RaisePropertyChanged("AverageRetailPriceAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string VehicleOriginalCostNewAmount {
            get {
                return this.vehicleOriginalCostNewAmountField;
            }
            set {
                this.vehicleOriginalCostNewAmountField = value;
                this.RaisePropertyChanged("VehicleOriginalCostNewAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string PassiveRestraintCode {
            get {
                return this.passiveRestraintCodeField;
            }
            set {
                this.passiveRestraintCodeField = value;
                this.RaisePropertyChanged("PassiveRestraintCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string AntiLockBrakeCode {
            get {
                return this.antiLockBrakeCodeField;
            }
            set {
                this.antiLockBrakeCodeField = value;
                this.RaisePropertyChanged("AntiLockBrakeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string DaytimeRunningLightsCode {
            get {
                return this.daytimeRunningLightsCodeField;
            }
            set {
                this.daytimeRunningLightsCodeField = value;
                this.RaisePropertyChanged("DaytimeRunningLightsCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string VehicleBodyTypeDescription {
            get {
                return this.vehicleBodyTypeDescriptionField;
            }
            set {
                this.vehicleBodyTypeDescriptionField = value;
                this.RaisePropertyChanged("VehicleBodyTypeDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string ISOAntiTheftDeviceCode {
            get {
                return this.iSOAntiTheftDeviceCodeField;
            }
            set {
                this.iSOAntiTheftDeviceCodeField = value;
                this.RaisePropertyChanged("ISOAntiTheftDeviceCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string VehiclePersonalInjuryProtectionSymbol {
            get {
                return this.vehiclePersonalInjuryProtectionSymbolField;
            }
            set {
                this.vehiclePersonalInjuryProtectionSymbolField = value;
                this.RaisePropertyChanged("VehiclePersonalInjuryProtectionSymbol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string VehicleLiabilitySymbol {
            get {
                return this.vehicleLiabilitySymbolField;
            }
            set {
                this.vehicleLiabilitySymbolField = value;
                this.RaisePropertyChanged("VehicleLiabilitySymbol");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cpi/policy/get_expanded_vin_information_output_epl2x1")]
    public partial class GetExpandedVINInformationOutput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private VINInformation vINInformationField;
        
        private Error errorInformationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public VINInformation VINInformation {
            get {
                return this.vINInformationField;
            }
            set {
                this.vINInformationField = value;
                this.RaisePropertyChanged("VINInformation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Error ErrorInformation {
            get {
                return this.errorInformationField;
            }
            set {
                this.errorInformationField = value;
                this.RaisePropertyChanged("ErrorInformation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cpi/policy/get_expanded_vin_information_list_reply_epl2x1")]
    public partial class GetExpandedVINInformationListReply : object, System.ComponentModel.INotifyPropertyChanged {
        
        private GetExpandedVINInformationOutput[] getExpandedVINInformationOutputField;
        
        private StatusInformation highLevelStatusInformationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GetExpandedVINInformationOutput", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public GetExpandedVINInformationOutput[] GetExpandedVINInformationOutput {
            get {
                return this.getExpandedVINInformationOutputField;
            }
            set {
                this.getExpandedVINInformationOutputField = value;
                this.RaisePropertyChanged("GetExpandedVINInformationOutput");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public StatusInformation HighLevelStatusInformation {
            get {
                return this.highLevelStatusInformationField;
            }
            set {
                this.highLevelStatusInformationField = value;
                this.RaisePropertyChanged("HighLevelStatusInformation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cpi/policy/get_expanded_vin_information_input_epl2x1")]
    public partial class GetExpandedVINInformationInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vehicleIdentificationNumberField;
        
        private string manufacturersNameField;
        
        private string modelNameField;
        
        private string modelYearField;
        
        private string postalStateAbbreviationField;
        
        private string stateOrProvinceCodeField;
        
        private System.DateTime rateDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string VehicleIdentificationNumber {
            get {
                return this.vehicleIdentificationNumberField;
            }
            set {
                this.vehicleIdentificationNumberField = value;
                this.RaisePropertyChanged("VehicleIdentificationNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ManufacturersName {
            get {
                return this.manufacturersNameField;
            }
            set {
                this.manufacturersNameField = value;
                this.RaisePropertyChanged("ManufacturersName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ModelName {
            get {
                return this.modelNameField;
            }
            set {
                this.modelNameField = value;
                this.RaisePropertyChanged("ModelName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ModelYear {
            get {
                return this.modelYearField;
            }
            set {
                this.modelYearField = value;
                this.RaisePropertyChanged("ModelYear");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string PostalStateAbbreviation {
            get {
                return this.postalStateAbbreviationField;
            }
            set {
                this.postalStateAbbreviationField = value;
                this.RaisePropertyChanged("PostalStateAbbreviation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string StateOrProvinceCode {
            get {
                return this.stateOrProvinceCodeField;
            }
            set {
                this.stateOrProvinceCodeField = value;
                this.RaisePropertyChanged("StateOrProvinceCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=6)]
        public System.DateTime RateDate {
            get {
                return this.rateDateField;
            }
            set {
                this.rateDateField = value;
                this.RaisePropertyChanged("RateDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cpi/policy/vin_information_retrieval_epl2x1", ConfigurationName="IccVinService.VINInformationRetrievalEPL2X1")]
    public interface VINInformationRetrievalEPL2X1 {
        
        // CODEGEN: Generating message contract since the operation GetExpandedVINInformationList is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(BlackBookHitChoice.IccVinService.SimpleFault), Action="", Name="getExpandedVINInformationListFault1_SimpleFaultReply")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BlackBookHitChoice.IccVinService.GetExpandedVINInformationListResponse1 GetExpandedVINInformationList(BlackBookHitChoice.IccVinService.GetExpandedVINInformationListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<BlackBookHitChoice.IccVinService.GetExpandedVINInformationListResponse1> GetExpandedVINInformationListAsync(BlackBookHitChoice.IccVinService.GetExpandedVINInformationListRequest request);
        
        // CODEGEN: Generating message contract since the operation SearchVINInformationByCriteria is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(BlackBookHitChoice.IccVinService.SimpleFault), Action="", Name="searchVINInformationByCriteriaFault1_SimpleFaultReply")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BlackBookHitChoice.IccVinService.SearchVINInformationByCriteriaResponse1 SearchVINInformationByCriteria(BlackBookHitChoice.IccVinService.SearchVINInformationByCriteriaRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<BlackBookHitChoice.IccVinService.SearchVINInformationByCriteriaResponse1> SearchVINInformationByCriteriaAsync(BlackBookHitChoice.IccVinService.SearchVINInformationByCriteriaRequest1 request);
        
        // CODEGEN: Generating message contract since the operation GetBestMatchVINInformationList is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(BlackBookHitChoice.IccVinService.SimpleFault), Action="", Name="getBestMatchVINInformationListFault1_SimpleFaultReply")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BlackBookHitChoice.IccVinService.GetBestMatchVINInformationListResponse1 GetBestMatchVINInformationList(BlackBookHitChoice.IccVinService.GetBestMatchVINInformationListRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<BlackBookHitChoice.IccVinService.GetBestMatchVINInformationListResponse1> GetBestMatchVINInformationListAsync(BlackBookHitChoice.IccVinService.GetBestMatchVINInformationListRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cpi/policy/vin_information_retrieval_epl2x1")]
    public partial class GetExpandedVINInformationList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private GetExpandedVINInformationInput[] getExpandedVINInformationListRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public GetExpandedVINInformationInput[] GetExpandedVINInformationListRequest {
            get {
                return this.getExpandedVINInformationListRequestField;
            }
            set {
                this.getExpandedVINInformationListRequestField = value;
                this.RaisePropertyChanged("GetExpandedVINInformationListRequest");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cpi/policy/vin_information_retrieval_epl2x1")]
    public partial class GetExpandedVINInformationListResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private GetExpandedVINInformationListReply getExpandedVINInformationListReplyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public GetExpandedVINInformationListReply GetExpandedVINInformationListReply {
            get {
                return this.getExpandedVINInformationListReplyField;
            }
            set {
                this.getExpandedVINInformationListReplyField = value;
                this.RaisePropertyChanged("GetExpandedVINInformationListReply");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExpandedVINInformationListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cpi/policy/vin_information_retrieval_epl2x1", Order=0)]
        public BlackBookHitChoice.IccVinService.GetExpandedVINInformationList GetExpandedVINInformationList;
        
        public GetExpandedVINInformationListRequest() {
        }
        
        public GetExpandedVINInformationListRequest(BlackBookHitChoice.IccVinService.GetExpandedVINInformationList GetExpandedVINInformationList) {
            this.GetExpandedVINInformationList = GetExpandedVINInformationList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExpandedVINInformationListResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cpi/policy/vin_information_retrieval_epl2x1", Order=0)]
        public BlackBookHitChoice.IccVinService.GetExpandedVINInformationListResponse GetExpandedVINInformationListResponse;
        
        public GetExpandedVINInformationListResponse1() {
        }
        
        public GetExpandedVINInformationListResponse1(BlackBookHitChoice.IccVinService.GetExpandedVINInformationListResponse GetExpandedVINInformationListResponse) {
            this.GetExpandedVINInformationListResponse = GetExpandedVINInformationListResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cpi/policy/vin_information_retrieval_epl2x1")]
    public partial class SearchVINInformationByCriteria : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SearchVINInformationByCriteriaRequest searchVINInformationByCriteriaRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public SearchVINInformationByCriteriaRequest SearchVINInformationByCriteriaRequest {
            get {
                return this.searchVINInformationByCriteriaRequestField;
            }
            set {
                this.searchVINInformationByCriteriaRequestField = value;
                this.RaisePropertyChanged("SearchVINInformationByCriteriaRequest");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cpi/policy/search_vin_information_by_criteria_request_epl2x1")]
    public partial class SearchVINInformationByCriteriaRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string partialVehicleIdentificationNumberField;
        
        private string manufacturersNameField;
        
        private string modelNameField;
        
        private string modelYearField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PartialVehicleIdentificationNumber {
            get {
                return this.partialVehicleIdentificationNumberField;
            }
            set {
                this.partialVehicleIdentificationNumberField = value;
                this.RaisePropertyChanged("PartialVehicleIdentificationNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ManufacturersName {
            get {
                return this.manufacturersNameField;
            }
            set {
                this.manufacturersNameField = value;
                this.RaisePropertyChanged("ManufacturersName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ModelName {
            get {
                return this.modelNameField;
            }
            set {
                this.modelNameField = value;
                this.RaisePropertyChanged("ModelName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ModelYear {
            get {
                return this.modelYearField;
            }
            set {
                this.modelYearField = value;
                this.RaisePropertyChanged("ModelYear");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cpi/policy/vin_information_retrieval_epl2x1")]
    public partial class SearchVINInformationByCriteriaResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SearchVINInformationByCriteriaReply searchVINInformationByCriteriaReplyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public SearchVINInformationByCriteriaReply SearchVINInformationByCriteriaReply {
            get {
                return this.searchVINInformationByCriteriaReplyField;
            }
            set {
                this.searchVINInformationByCriteriaReplyField = value;
                this.RaisePropertyChanged("SearchVINInformationByCriteriaReply");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cpi/policy/search_vin_information_by_criteria_reply_epl2x1")]
    public partial class SearchVINInformationByCriteriaReply : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SearchVINInformationByCriteriaOutput searchVINInformationByCriteriaOutputField;
        
        private StatusInformation highLevelStatusInformationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public SearchVINInformationByCriteriaOutput SearchVINInformationByCriteriaOutput {
            get {
                return this.searchVINInformationByCriteriaOutputField;
            }
            set {
                this.searchVINInformationByCriteriaOutputField = value;
                this.RaisePropertyChanged("SearchVINInformationByCriteriaOutput");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public StatusInformation HighLevelStatusInformation {
            get {
                return this.highLevelStatusInformationField;
            }
            set {
                this.highLevelStatusInformationField = value;
                this.RaisePropertyChanged("HighLevelStatusInformation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cpi/policy/search_vin_information_by_criteria_output_epl2x1")]
    public partial class SearchVINInformationByCriteriaOutput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private VINInformation[] vINInformationField;
        
        private Error errorInformationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VINInformation", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public VINInformation[] VINInformation {
            get {
                return this.vINInformationField;
            }
            set {
                this.vINInformationField = value;
                this.RaisePropertyChanged("VINInformation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Error ErrorInformation {
            get {
                return this.errorInformationField;
            }
            set {
                this.errorInformationField = value;
                this.RaisePropertyChanged("ErrorInformation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchVINInformationByCriteriaRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cpi/policy/vin_information_retrieval_epl2x1", Order=0)]
        public BlackBookHitChoice.IccVinService.SearchVINInformationByCriteria SearchVINInformationByCriteria;
        
        public SearchVINInformationByCriteriaRequest1() {
        }
        
        public SearchVINInformationByCriteriaRequest1(BlackBookHitChoice.IccVinService.SearchVINInformationByCriteria SearchVINInformationByCriteria) {
            this.SearchVINInformationByCriteria = SearchVINInformationByCriteria;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchVINInformationByCriteriaResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cpi/policy/vin_information_retrieval_epl2x1", Order=0)]
        public BlackBookHitChoice.IccVinService.SearchVINInformationByCriteriaResponse SearchVINInformationByCriteriaResponse;
        
        public SearchVINInformationByCriteriaResponse1() {
        }
        
        public SearchVINInformationByCriteriaResponse1(BlackBookHitChoice.IccVinService.SearchVINInformationByCriteriaResponse SearchVINInformationByCriteriaResponse) {
            this.SearchVINInformationByCriteriaResponse = SearchVINInformationByCriteriaResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cpi/policy/vin_information_retrieval_epl2x1")]
    public partial class GetBestMatchVINInformationList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private GetBestMatchVINInformationListRequest getBestMatchVINInformationListRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public GetBestMatchVINInformationListRequest GetBestMatchVINInformationListRequest {
            get {
                return this.getBestMatchVINInformationListRequestField;
            }
            set {
                this.getBestMatchVINInformationListRequestField = value;
                this.RaisePropertyChanged("GetBestMatchVINInformationListRequest");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cpi/policy/get_best_match_vin_information_list_request_epl2x1")]
    public partial class GetBestMatchVINInformationListRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vINSearchTypeNameField;
        
        private GetBestMatchVINInformationInput[] getBestMatchVINInformationInputField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string VINSearchTypeName {
            get {
                return this.vINSearchTypeNameField;
            }
            set {
                this.vINSearchTypeNameField = value;
                this.RaisePropertyChanged("VINSearchTypeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GetBestMatchVINInformationInput", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public GetBestMatchVINInformationInput[] GetBestMatchVINInformationInput {
            get {
                return this.getBestMatchVINInformationInputField;
            }
            set {
                this.getBestMatchVINInformationInputField = value;
                this.RaisePropertyChanged("GetBestMatchVINInformationInput");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cpi/policy/get_best_match_vin_information_input_epl2x1")]
    public partial class GetBestMatchVINInformationInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vehicleIdentificationNumberField;
        
        private string manufacturersNameField;
        
        private string modelNameField;
        
        private string modelYearField;
        
        private string postalStateAbbreviationField;
        
        private string stateOrProvinceCodeField;
        
        private System.DateTime rateDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string VehicleIdentificationNumber {
            get {
                return this.vehicleIdentificationNumberField;
            }
            set {
                this.vehicleIdentificationNumberField = value;
                this.RaisePropertyChanged("VehicleIdentificationNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ManufacturersName {
            get {
                return this.manufacturersNameField;
            }
            set {
                this.manufacturersNameField = value;
                this.RaisePropertyChanged("ManufacturersName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ModelName {
            get {
                return this.modelNameField;
            }
            set {
                this.modelNameField = value;
                this.RaisePropertyChanged("ModelName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ModelYear {
            get {
                return this.modelYearField;
            }
            set {
                this.modelYearField = value;
                this.RaisePropertyChanged("ModelYear");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string PostalStateAbbreviation {
            get {
                return this.postalStateAbbreviationField;
            }
            set {
                this.postalStateAbbreviationField = value;
                this.RaisePropertyChanged("PostalStateAbbreviation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string StateOrProvinceCode {
            get {
                return this.stateOrProvinceCodeField;
            }
            set {
                this.stateOrProvinceCodeField = value;
                this.RaisePropertyChanged("StateOrProvinceCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=6)]
        public System.DateTime RateDate {
            get {
                return this.rateDateField;
            }
            set {
                this.rateDateField = value;
                this.RaisePropertyChanged("RateDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cpi/policy/vin_information_retrieval_epl2x1")]
    public partial class GetBestMatchVINInformationListResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private GetBestMatchVINInformationListReply getBestMatchVINInformationListReplyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public GetBestMatchVINInformationListReply GetBestMatchVINInformationListReply {
            get {
                return this.getBestMatchVINInformationListReplyField;
            }
            set {
                this.getBestMatchVINInformationListReplyField = value;
                this.RaisePropertyChanged("GetBestMatchVINInformationListReply");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cpi/policy/get_best_match_vin_information_list_reply_epl2x1")]
    public partial class GetBestMatchVINInformationListReply : object, System.ComponentModel.INotifyPropertyChanged {
        
        private GetBestMatchVINInformationOutput[] getBestMatchVINInformationOutputField;
        
        private StatusInformation highLevelStatusInformationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GetBestMatchVINInformationOutput", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public GetBestMatchVINInformationOutput[] GetBestMatchVINInformationOutput {
            get {
                return this.getBestMatchVINInformationOutputField;
            }
            set {
                this.getBestMatchVINInformationOutputField = value;
                this.RaisePropertyChanged("GetBestMatchVINInformationOutput");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public StatusInformation HighLevelStatusInformation {
            get {
                return this.highLevelStatusInformationField;
            }
            set {
                this.highLevelStatusInformationField = value;
                this.RaisePropertyChanged("HighLevelStatusInformation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cpi/policy/get_best_match_vin_information_output_epl2x1")]
    public partial class GetBestMatchVINInformationOutput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vINSearchMatchTypeNameField;
        
        private VINInformation vINInformationField;
        
        private Error errorInformationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string VINSearchMatchTypeName {
            get {
                return this.vINSearchMatchTypeNameField;
            }
            set {
                this.vINSearchMatchTypeNameField = value;
                this.RaisePropertyChanged("VINSearchMatchTypeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public VINInformation VINInformation {
            get {
                return this.vINInformationField;
            }
            set {
                this.vINInformationField = value;
                this.RaisePropertyChanged("VINInformation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public Error ErrorInformation {
            get {
                return this.errorInformationField;
            }
            set {
                this.errorInformationField = value;
                this.RaisePropertyChanged("ErrorInformation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBestMatchVINInformationListRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cpi/policy/vin_information_retrieval_epl2x1", Order=0)]
        public BlackBookHitChoice.IccVinService.GetBestMatchVINInformationList GetBestMatchVINInformationList;
        
        public GetBestMatchVINInformationListRequest1() {
        }
        
        public GetBestMatchVINInformationListRequest1(BlackBookHitChoice.IccVinService.GetBestMatchVINInformationList GetBestMatchVINInformationList) {
            this.GetBestMatchVINInformationList = GetBestMatchVINInformationList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBestMatchVINInformationListResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cpi/policy/vin_information_retrieval_epl2x1", Order=0)]
        public BlackBookHitChoice.IccVinService.GetBestMatchVINInformationListResponse GetBestMatchVINInformationListResponse;
        
        public GetBestMatchVINInformationListResponse1() {
        }
        
        public GetBestMatchVINInformationListResponse1(BlackBookHitChoice.IccVinService.GetBestMatchVINInformationListResponse GetBestMatchVINInformationListResponse) {
            this.GetBestMatchVINInformationListResponse = GetBestMatchVINInformationListResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VINInformationRetrievalEPL2X1Channel : BlackBookHitChoice.IccVinService.VINInformationRetrievalEPL2X1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VINInformationRetrievalEPL2X1Client : System.ServiceModel.ClientBase<BlackBookHitChoice.IccVinService.VINInformationRetrievalEPL2X1>, BlackBookHitChoice.IccVinService.VINInformationRetrievalEPL2X1 {
        
        public VINInformationRetrievalEPL2X1Client() {
        }
        
        public VINInformationRetrievalEPL2X1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VINInformationRetrievalEPL2X1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VINInformationRetrievalEPL2X1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VINInformationRetrievalEPL2X1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlackBookHitChoice.IccVinService.GetExpandedVINInformationListResponse1 BlackBookHitChoice.IccVinService.VINInformationRetrievalEPL2X1.GetExpandedVINInformationList(BlackBookHitChoice.IccVinService.GetExpandedVINInformationListRequest request) {
            return base.Channel.GetExpandedVINInformationList(request);
        }
        
        public BlackBookHitChoice.IccVinService.GetExpandedVINInformationListResponse GetExpandedVINInformationList(BlackBookHitChoice.IccVinService.GetExpandedVINInformationList GetExpandedVINInformationList1) {
            BlackBookHitChoice.IccVinService.GetExpandedVINInformationListRequest inValue = new BlackBookHitChoice.IccVinService.GetExpandedVINInformationListRequest();
            inValue.GetExpandedVINInformationList = GetExpandedVINInformationList1;
            BlackBookHitChoice.IccVinService.GetExpandedVINInformationListResponse1 retVal = ((BlackBookHitChoice.IccVinService.VINInformationRetrievalEPL2X1)(this)).GetExpandedVINInformationList(inValue);
            return retVal.GetExpandedVINInformationListResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlackBookHitChoice.IccVinService.GetExpandedVINInformationListResponse1> BlackBookHitChoice.IccVinService.VINInformationRetrievalEPL2X1.GetExpandedVINInformationListAsync(BlackBookHitChoice.IccVinService.GetExpandedVINInformationListRequest request) {
            return base.Channel.GetExpandedVINInformationListAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlackBookHitChoice.IccVinService.GetExpandedVINInformationListResponse1> GetExpandedVINInformationListAsync(BlackBookHitChoice.IccVinService.GetExpandedVINInformationList GetExpandedVINInformationList) {
            BlackBookHitChoice.IccVinService.GetExpandedVINInformationListRequest inValue = new BlackBookHitChoice.IccVinService.GetExpandedVINInformationListRequest();
            inValue.GetExpandedVINInformationList = GetExpandedVINInformationList;
            return ((BlackBookHitChoice.IccVinService.VINInformationRetrievalEPL2X1)(this)).GetExpandedVINInformationListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlackBookHitChoice.IccVinService.SearchVINInformationByCriteriaResponse1 BlackBookHitChoice.IccVinService.VINInformationRetrievalEPL2X1.SearchVINInformationByCriteria(BlackBookHitChoice.IccVinService.SearchVINInformationByCriteriaRequest1 request) {
            return base.Channel.SearchVINInformationByCriteria(request);
        }
        
        public BlackBookHitChoice.IccVinService.SearchVINInformationByCriteriaResponse SearchVINInformationByCriteria(BlackBookHitChoice.IccVinService.SearchVINInformationByCriteria SearchVINInformationByCriteria1) {
            BlackBookHitChoice.IccVinService.SearchVINInformationByCriteriaRequest1 inValue = new BlackBookHitChoice.IccVinService.SearchVINInformationByCriteriaRequest1();
            inValue.SearchVINInformationByCriteria = SearchVINInformationByCriteria1;
            BlackBookHitChoice.IccVinService.SearchVINInformationByCriteriaResponse1 retVal = ((BlackBookHitChoice.IccVinService.VINInformationRetrievalEPL2X1)(this)).SearchVINInformationByCriteria(inValue);
            return retVal.SearchVINInformationByCriteriaResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlackBookHitChoice.IccVinService.SearchVINInformationByCriteriaResponse1> BlackBookHitChoice.IccVinService.VINInformationRetrievalEPL2X1.SearchVINInformationByCriteriaAsync(BlackBookHitChoice.IccVinService.SearchVINInformationByCriteriaRequest1 request) {
            return base.Channel.SearchVINInformationByCriteriaAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlackBookHitChoice.IccVinService.SearchVINInformationByCriteriaResponse1> SearchVINInformationByCriteriaAsync(BlackBookHitChoice.IccVinService.SearchVINInformationByCriteria SearchVINInformationByCriteria) {
            BlackBookHitChoice.IccVinService.SearchVINInformationByCriteriaRequest1 inValue = new BlackBookHitChoice.IccVinService.SearchVINInformationByCriteriaRequest1();
            inValue.SearchVINInformationByCriteria = SearchVINInformationByCriteria;
            return ((BlackBookHitChoice.IccVinService.VINInformationRetrievalEPL2X1)(this)).SearchVINInformationByCriteriaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlackBookHitChoice.IccVinService.GetBestMatchVINInformationListResponse1 BlackBookHitChoice.IccVinService.VINInformationRetrievalEPL2X1.GetBestMatchVINInformationList(BlackBookHitChoice.IccVinService.GetBestMatchVINInformationListRequest1 request) {
            return base.Channel.GetBestMatchVINInformationList(request);
        }
        
        public BlackBookHitChoice.IccVinService.GetBestMatchVINInformationListResponse GetBestMatchVINInformationList(BlackBookHitChoice.IccVinService.GetBestMatchVINInformationList GetBestMatchVINInformationList1) {
            BlackBookHitChoice.IccVinService.GetBestMatchVINInformationListRequest1 inValue = new BlackBookHitChoice.IccVinService.GetBestMatchVINInformationListRequest1();
            inValue.GetBestMatchVINInformationList = GetBestMatchVINInformationList1;
            BlackBookHitChoice.IccVinService.GetBestMatchVINInformationListResponse1 retVal = ((BlackBookHitChoice.IccVinService.VINInformationRetrievalEPL2X1)(this)).GetBestMatchVINInformationList(inValue);
            return retVal.GetBestMatchVINInformationListResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlackBookHitChoice.IccVinService.GetBestMatchVINInformationListResponse1> BlackBookHitChoice.IccVinService.VINInformationRetrievalEPL2X1.GetBestMatchVINInformationListAsync(BlackBookHitChoice.IccVinService.GetBestMatchVINInformationListRequest1 request) {
            return base.Channel.GetBestMatchVINInformationListAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlackBookHitChoice.IccVinService.GetBestMatchVINInformationListResponse1> GetBestMatchVINInformationListAsync(BlackBookHitChoice.IccVinService.GetBestMatchVINInformationList GetBestMatchVINInformationList) {
            BlackBookHitChoice.IccVinService.GetBestMatchVINInformationListRequest1 inValue = new BlackBookHitChoice.IccVinService.GetBestMatchVINInformationListRequest1();
            inValue.GetBestMatchVINInformationList = GetBestMatchVINInformationList;
            return ((BlackBookHitChoice.IccVinService.VINInformationRetrievalEPL2X1)(this)).GetBestMatchVINInformationListAsync(inValue);
        }
    }
}
